name: Run Dagger Pipeline Manually

on:
  workflow_dispatch:  

jobs:
  run-dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dagger for GitHub
        uses: dagger/dagger-for-github@v5.6.0
        with:
          verb: call 
          module: github.com/your-username/your-repo/path/to/your/module
          args: run_pipeline
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          TEXTBELT_KEY: ${{ secrets.TEXTBELT_KEY }}
          MOBILE_NUMS: '+15162341744,+15512259418'
          DATABASE: 'financial_data'
          COLLECTION: 'transactions'
