name: Run Dagger Pipeline Manually

on:
  workflow_dispatch:  

jobs:
  run-dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Dagger
        run: pip install dagger
      
      - name: Run Dagger Pipeline
        run: python dagger/src/main/__init__.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          TEXTBELT_KEY: ${{ secrets.TEXTBELT_KEY }}
          MOBILE_NUMS: '+1234567890,+0987654321'
          DATABASE: 'financial_data'
          COLLECTION: 'transactions'
